// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PilotService.Data;

#nullable disable

namespace PilotService.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    /// <inheritdoc />
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("PilotService.Data.Entities.Employee", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("display_name");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("email");

                b.Property<int?>("ManagerId")
                    .HasColumnType("integer")
                    .HasColumnName("manager_id");

                b.Property<int>("RoleId")
                    .HasColumnType("integer")
                    .HasColumnName("role_id");

                b.HasKey("Id")
                    .HasName("pk_employees");

                b.HasIndex("Email")
                    .IsUnique()
                    .HasDatabaseName("ux_employees_email");

                b.HasIndex("ManagerId")
                    .HasDatabaseName("ix_employees_manager_id");

                b.HasIndex("RoleId")
                    .HasDatabaseName("ix_employees_role_id");

                b.ToTable("employees", (string)null);
            });

        modelBuilder.Entity("PilotService.Data.Entities.Role", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("code");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.HasKey("Id")
                    .HasName("pk_roles");

                b.HasIndex("Code")
                    .IsUnique()
                    .HasDatabaseName("ux_roles_code");

                b.ToTable("roles", (string)null);
            });

        modelBuilder.Entity("PilotService.Data.Entities.Employee", b =>
            {
                b.HasOne("PilotService.Data.Entities.Employee", "Manager")
                    .WithMany("Reports")
                    .HasForeignKey("ManagerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("fk_employees_employees_manager_id");

                b.HasOne("PilotService.Data.Entities.Role", "Role")
                    .WithMany("Employees")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_employees_roles_role_id");

                b.Navigation("Manager");

                b.Navigation("Role");
            });

        modelBuilder.Entity("PilotService.Data.Entities.Employee", b =>
            {
                b.Navigation("Reports");
            });

        modelBuilder.Entity("PilotService.Data.Entities.Role", b =>
            {
                b.Navigation("Employees");
            });
#pragma warning restore 612, 618
    }
}
